# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161210151906 on 2016-12-16 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_cost',
        ),
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
