# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170304_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
