# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
