# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_likes_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=1000),
        ),
    ]
